### ISSUE TITLE
Breaks user preferences... 

### ISSUE THREAD

**Issue by dtordable** [collective/collective.registrationcaptcha#2]
When I try to modify user preferences get this traceback:

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module z3c.form.form, line 218, in **call**
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 21, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in **call**
  Module z3c.form.button, line 170, in **call**
  Module plone.app.users.browser.account, line 147, in handleSave
  Module plone.app.users.browser.account, line 130, in validate_email
KeyError: 'email'

**Comment by thet** [comment]
Which version of plone.app.users do you have? You need 2.1.0. I don't know, if this solves anything, but it's a start...

**Comment by krish0005** [comment]
If it can be of any help, iI had to pin:

plone.app.users = 2.1.0
plone.formwidget.namedfile = 1.0.3

But then got the following:

```
==> worker-stdout---supervisor-sSwnHF.log <==
Traceback (most recent call last):
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/Zope2/Startup/__init__.py", line 86, in prepare
    self.startZope()
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/Zope2/Startup/__init__.py", line 259, in startZope
    Zope2.startup()
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/Zope2/App/startup.py", line 118, in startup
    load_zcml()
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/Zope2/App/startup.py", line 52, in load_zcml
    load_site()
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/Zope2/App/zcml.py", line 46, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 649, in file
    include(context, name, package)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/zope/PLUMI/plumi.app/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/home/zope/PLUMI/plumi.app/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/zope/PLUMI/plumi.app/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/home/zope/PLUMI/plumi.app/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/zope/PLUMI/plumi.app/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/home/zope/PLUMI/plumi.app/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/home/zope/PLUMI/plumi.app/eggs/grokcore.component-1.9-py2.7.egg/grokcore/component/zcml.py", line 57, in grokDirective
    do_grok(package.__name__, _context, extra_exclude=exclude)
  File "/home/zope/PLUMI/plumi.app/eggs/grokcore.component-1.9-py2.7.egg/grokcore/component/zcml.py", line 71, in do_grok
    config=config)
  File "/home/zope/PLUMI/plumi.app/eggs/martian-0.11.3-py2.7.egg/martian/core.py", line 201, in grok_dotted_name
    grok_package(module_info, grokker, **kw)
  File "/home/zope/PLUMI/plumi.app/eggs/martian-0.11.3-py2.7.egg/martian/core.py", line 206, in grok_package
    grok_package(sub_module_info, grokker, **kw)
  File "/home/zope/PLUMI/plumi.app/eggs/martian-0.11.3-py2.7.egg/martian/core.py", line 204, in grok_package
    grok_module(module_info, grokker, **kw)
  File "/home/zope/PLUMI/plumi.app/eggs/martian-0.11.3-py2.7.egg/martian/core.py", line 209, in grok_module
    grokker.grok(module_info.dotted_name, module_info.getModule(),
  File "/home/zope/PLUMI/plumi.app/eggs/martian-0.11.3-py2.7.egg/martian/scan.py", line 141, in getModule
    self._module = resolve(self.dotted_name)
  File "/home/zope/PLUMI/plumi.app/eggs/martian-0.11.3-py2.7.egg/martian/scan.py", line 217, in resolve
    __import__(used)
  File "/home/zope/PLUMI/plumi.app/eggs/plumi.skin-4.5-py2.7.egg/plumi/skin/adapter.py", line 1, in <module>
    from plone.app.users.browser.personalpreferences import UserDataPanelAdapter
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/home/zope/PLUMI/plumi.app/parts/worker/etc/site.zcml", line 15.2-15.55
    ZopeXMLConfigurationError: File "/home/zope/PLUMI/plumi.app/parts/worker/etc/package-includes/003-plumi.skin-configure.zcml", line 1.0-1.54
    ZopeXMLConfigurationError: File "/home/zope/PLUMI/plumi.app/eggs/plumi.skin-4.5-py2.7.egg/plumi/skin/configure.zcml", line 14.2-14.27
    ImportError: cannot import name UserDataPanelAdapter
```
I haven't been able to run collective.registrationcaptcha succesfully yet.

Note: i'm also using plone.formwidget.recaptcha (it works but still testing it) but i'd really love to have it also in the registration form to stop the continuous spam..

I have:

Plone 4.2.0.1 (4206)
CMF 2.2.6
Zope 2.13.15
Python 2.7.9 (default, Jun 29 2016, 13:11:10) [GCC 4.9.2]
PIL 2.2.1 (Pillow)
